# Generated by Django 6.0.4 on 2026-04-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=300)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("num_reviews", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=200, null=True)),
                ("book_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("price", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "availability",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("source_books", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "genre_prediction",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sentiment", models.CharField(blank=True, max_length=100, null=True)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("recommendations", models.JSONField(blank=True, null=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
